# Node, Mongo, Redis, Nginx

version: "3"
services:
  ui-interactions-api:
    image: node
    depends_on:
      - mongodb
    ports:
      - "4050:4050"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx
    depends_on:
      - ui-interactions-api
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:

volumes:
  mongodb: